### ISSUE TITLE
Error get_video e url object

### ISSUE THREAD

**Issue by alias-lucas** [v4p0r/gengar#3]
Error

**Comment by brunocsouzasantos** [comment]
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at main (/var/www/html/gengar/index.js:35:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by marcosdsdba** [comment]
> undefined:1
> 
> SyntaxError: Unexpected end of JSON input at JSON.parse () at main (/var/www/html/gengar/index.js:35:22) at processTicksAndRejections (node:internal/process/task_queues:96:5)

[brunocsouzasantos](https://github.com/brunocsouzasantos) Corrigi o bug olha lá no meu github, usei hoje 05/ABR/2022.  Bom uso : https://github.com/marcosdsdba/alura-gap/
